global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
    metrics_path: '/metrics'
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:6777']
  - job_name: node-exporter
    static_configs:
      - targets: ['localhost:6777']